# Basic Operations With Matrices

### Import numpy

In [1]:
import numpy as np


### Create vector

In [2]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [5]:
type(x)

numpy.ndarray

### Make a 3x2 Matrix

In [3]:
A = np.array([[1,2],[3,4],[5,6]]) 
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
type(A)

numpy.ndarray

In [6]:
# Check shaoe
A.shape

(3, 2)

In [7]:
x.shape

(4,)

## Transposition of a Matrix

In [8]:
# we can access the tranpsoe methpd by
A_T = A.T
A_T

array([[1, 3, 5],
       [2, 4, 6]])

In [10]:
# or 
A_T = A.transpose()
A_T

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
# check dimesnions, the number of columns and rows should switch
A_T.shape

(2, 3)

## Matrix Addition

In [12]:
B = np.array([[2, 5], [7, 4], [4, 3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [14]:
# Add the matrix A to Matrix B
C = A + B 
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [15]:
# It is also possible to add a scalar, which adds the scalar to each cell of matrix
D = A + 1 
D

array([[2, 3],
       [4, 5],
       [6, 7]])

## Matrix Multiplication

In [16]:
# Define a matri A
A = np.array([[1, 2], [3, 4], [5, 6]]) 
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
# Define a matrix B
B = np.array([[2], [4]]) 
B

array([[2],
       [4]])

In [19]:
# B/c A has 2 columsn and B has 2 rows we can multiple them
C = np.dot(A, B) 
C

array([[10],
       [22],
       [34]])

In [21]:
# another way to write their dot product
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

In [22]:
# check the shape
C.shape

(3, 1)

## Identity Matrices

In [23]:
# Can  creat an identity matrix with numpy eye function
I = np.eye(3) 
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

## Determinant

In [26]:
# To compute a determinant we use numpy linalg module
# Define a new matrix M with shape 2x2
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [27]:
# compute the determinant of matrix M
det_M = np.linalg.det(M) 
det_M


-2.0000000000000004

In [28]:
# must be  square matrix 
M = np.array([1,2],[3,4],[5,6])
det_M = np.linalg.det(M)
det_M

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

## Inverse Matrices

In [42]:
# Create matrix
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A 

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [43]:
# Cacl its inverse
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [44]:
# chekc if it really is the inverse 
I = A_inv.dot(A)
I

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])